// The role × route matrix and the portal routes, shared by
// permissions.test.ts (which checks each row) and routes.test.ts (which
// checks every registered route has a row).
import type { Role } from '../auth/tokens.js'

export type Method = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export const X = 'does-not-exist'

// [method, path, minimum role that passes the guard]
export const ROUTES: [Method, string, Role][] = [
  ['GET', '/academic-years', 'viewer'],
  ['POST', '/academic-years', 'scheduler'],
  ['POST', `/academic-years/${X}/set-current`, 'scheduler'],
  ['PUT', `/academic-years/${X}/terms`, 'scheduler'],
  ['GET', '/branches', 'viewer'],
  ['GET', '/classes', 'viewer'],
  ['POST', '/classes', 'admin'],
  ['POST', '/classes/bulk', 'admin'],
  ['PATCH', `/classes/${X}`, 'admin'],
  ['DELETE', `/classes/${X}`, 'admin'],
  ['GET', '/datasets/timetable', 'viewer'],
  ['PUT', '/datasets/timetable', 'scheduler'],
  ['GET', '/datasets/timetable/versions', 'viewer'],
  ['GET', '/datasets/timetable/versions/1', 'viewer'],
  ['GET', `/students/${X}/enrollments`, 'viewer'],
  ['POST', `/students/${X}/transfer`, 'admin'],
  ['POST', `/students/${X}/withdraw`, 'admin'],
  ['POST', '/enrollments/bulk-assign', 'admin'],
  ['POST', `/students/${X}/enrollments`, 'admin'],
  ['POST', `/enrollments/${X}/activate`, 'admin'],
  ['POST', `/enrollments/${X}/cancel`, 'admin'],
  ['GET', `/enrollments/rollover?branchId=${X}&fromYearId=${X}&toYearId=${X}`, 'admin'],
  ['POST', '/enrollments/rollover/preview', 'admin'],
  ['POST', '/enrollments/rollover/commit', 'admin'],
  ['POST', '/enrollments/rollover/start', 'admin'],
  ['GET', '/finance/fee-structures', 'viewer'],
  ['GET', `/finance/fee-structures/${X}`, 'viewer'],
  ['POST', '/finance/fee-structures', 'admin'],
  ['PATCH', `/finance/fee-structures/${X}`, 'admin'],
  ['POST', `/finance/fee-structures/${X}/deactivate`, 'admin'],
  ['GET', '/finance/invoices', 'viewer'],
  ['GET', `/finance/invoices/${X}`, 'viewer'],
  ['POST', '/finance/invoices', 'scheduler'],
  ['POST', `/finance/invoices/${X}/line-items`, 'scheduler'],
  ['PATCH', `/finance/invoices/${X}/line-items/${X}`, 'scheduler'],
  ['DELETE', `/finance/invoices/${X}/line-items/${X}`, 'scheduler'],
  ['POST', `/finance/invoices/${X}/void`, 'admin'],
  ['PUT', `/finance/invoices/${X}/installments`, 'scheduler'],
  ['GET', '/finance/payments', 'viewer'],
  ['POST', `/finance/invoices/${X}/payments`, 'scheduler'],
  ['POST', `/finance/payments/${X}/void`, 'admin'],
  ['GET', '/finance/receipts', 'viewer'],
  ['GET', `/finance/receipts/${X}`, 'viewer'],
  ['GET', `/finance/students/${X}/balance`, 'viewer'],
  // Phase 3 finance.
  ['GET', `/finance/students/${X}/open-invoices`, 'viewer'],
  ['POST', `/finance/students/${X}/payments`, 'scheduler'],
  ['POST', `/finance/payments/${X}/confirm`, 'admin'],
  ['POST', `/finance/payments/${X}/reject`, 'admin'],
  ['GET', '/finance/discount-types', 'viewer'],
  ['POST', '/finance/discount-types', 'admin'],
  ['PATCH', `/finance/discount-types/${X}`, 'admin'],
  ['POST', `/finance/invoices/${X}/adjustments`, 'admin'],
  ['DELETE', `/finance/invoices/${X}/adjustments/${X}`, 'admin'],
  ['GET', '/finance/scholarships', 'viewer'],
  ['GET', `/finance/scholarships/${X}`, 'viewer'],
  ['POST', '/finance/scholarships', 'scheduler'],
  ['POST', `/finance/scholarships/${X}/revoke`, 'admin'],
  ['GET', '/finance/refunds', 'viewer'],
  ['POST', `/finance/invoices/${X}/refunds`, 'scheduler'],
  ['POST', `/finance/refunds/${X}/pay`, 'admin'],
  ['POST', `/finance/refunds/${X}/cancel`, 'scheduler'],
  ['GET', '/finance/vendors', 'viewer'],
  ['POST', '/finance/vendors', 'scheduler'],
  ['PATCH', `/finance/vendors/${X}`, 'scheduler'],
  ['GET', '/finance/expenses', 'viewer'],
  ['GET', `/finance/expenses/${X}`, 'viewer'],
  ['POST', '/finance/expenses', 'scheduler'],
  ['POST', `/finance/expenses/${X}/pay`, 'admin'],
  ['POST', `/finance/expenses/${X}/cancel`, 'scheduler'],
  ['GET', '/finance/reports/summary?from=2026-01-01&to=2026-12-31', 'admin'],
  // Phase 4 HR. Leave requests, types and /hr/me are open to any member:
  // the handler decides (HR in the branch, or the employee themselves).
  ['GET', '/hr/employees', 'admin'],
  ['GET', `/hr/employees/${X}`, 'admin'],
  ['POST', '/hr/employees', 'admin'],
  ['PATCH', `/hr/employees/${X}`, 'admin'],
  ['POST', `/hr/employees/${X}/terminate`, 'admin'],
  ['POST', `/hr/employees/${X}/rehire`, 'admin'],
  ['PUT', `/hr/employees/${X}/user`, 'admin'],
  ['GET', `/hr/employees/${X}/history`, 'admin'],
  ['GET', `/hr/employees/${X}/contracts`, 'admin'],
  ['POST', `/hr/employees/${X}/contracts`, 'admin'],
  ['POST', `/hr/contracts/${X}/renew`, 'admin'],
  ['POST', `/hr/contracts/${X}/end`, 'admin'],
  ['GET', '/hr/contracts/expiring', 'admin'],
  ['GET', '/hr/leave-types', 'viewer'],
  ['POST', '/hr/leave-types', 'admin'],
  ['PATCH', `/hr/leave-types/${X}`, 'admin'],
  ['GET', `/hr/employees/${X}/leave`, 'admin'],
  ['POST', `/hr/employees/${X}/leave-adjustments`, 'admin'],
  ['GET', '/hr/me', 'viewer'],
  ['GET', '/hr/leave-requests', 'admin'],
  ['POST', '/hr/leave-requests', 'viewer'],
  ['POST', `/hr/leave-requests/${X}/cancel`, 'viewer'],
  ['GET', `/hr/attendance?branchId=${X}&date=2026-01-01`, 'admin'],
  ['PUT', '/hr/attendance', 'admin'],
  ['GET', `/hr/employees/${X}/attendance?from=2026-01-01&to=2026-01-31`, 'admin'],
  ['GET', '/hr/reports/summary?from=2026-01-01&to=2026-12-31', 'admin'],
  // Phase 5 operations.
  ['GET', '/ops/assets', 'scheduler'],
  ['GET', `/ops/assets/${X}`, 'scheduler'],
  ['POST', '/ops/assets', 'admin'],
  ['PATCH', `/ops/assets/${X}`, 'admin'],
  ['POST', `/ops/assets/${X}/assign`, 'admin'],
  ['POST', `/ops/assets/${X}/return`, 'admin'],
  ['POST', `/ops/assets/${X}/maintenance`, 'admin'],
  ['POST', `/ops/assets/${X}/transfer`, 'admin'],
  ['POST', `/ops/assets/${X}/dispose`, 'admin'],
  ['GET', '/ops/inventory/items', 'scheduler'],
  ['POST', '/ops/inventory/items', 'admin'],
  ['PATCH', `/ops/inventory/items/${X}`, 'admin'],
  ['GET', `/ops/inventory/items/${X}/movements`, 'scheduler'],
  ['POST', `/ops/inventory/items/${X}/movements`, 'admin'],
  ['GET', '/ops/suppliers', 'scheduler'],
  ['POST', '/ops/suppliers', 'admin'],
  ['GET', '/ops/facilities', 'scheduler'],
  ['POST', '/ops/buildings', 'admin'],
  ['PATCH', `/ops/buildings/${X}`, 'admin'],
  ['POST', '/ops/rooms', 'admin'],
  ['PATCH', `/ops/rooms/${X}`, 'admin'],
  ['GET', '/ops/maintenance', 'scheduler'],
  ['POST', '/ops/maintenance', 'scheduler'],
  ['PATCH', `/ops/maintenance/${X}`, 'scheduler'],
  ['GET', '/ops/transport/buses', 'viewer'],
  ['PUT', `/ops/transport/buses/${X}/details`, 'admin'],
  ['GET', '/ops/transport/drivers', 'viewer'],
  ['POST', '/ops/transport/drivers', 'admin'],
  ['PATCH', `/ops/transport/drivers/${X}`, 'admin'],
  ['GET', '/ops/transport/compliance', 'viewer'],
  ['GET', `/ops/transport/fees?branchId=${X}&academicYearId=${X}`, 'viewer'],
  ['PUT', '/ops/transport/fees', 'admin'],
  ['POST', '/ops/transport/fees/bill', 'admin'],
  ['GET', '/ops/library/settings', 'scheduler'],
  ['PUT', '/ops/library/settings', 'scheduler'],
  ['GET', '/ops/library/books', 'scheduler'],
  ['POST', '/ops/library/books', 'scheduler'],
  ['PATCH', `/ops/library/books/${X}`, 'scheduler'],
  ['POST', `/ops/library/books/${X}/copies`, 'scheduler'],
  ['POST', `/ops/library/copies/${X}/withdraw`, 'scheduler'],
  ['GET', '/ops/library/loans', 'scheduler'],
  ['POST', '/ops/library/loans', 'scheduler'],
  ['POST', `/ops/library/loans/${X}/return`, 'scheduler'],
  ['POST', `/ops/library/loans/${X}/renew`, 'scheduler'],
  ['POST', `/ops/library/loans/${X}/lost`, 'scheduler'],
  ['POST', `/ops/library/loans/${X}/pay`, 'scheduler'],
  ['POST', `/ops/library/loans/${X}/waive`, 'scheduler'],
  ['GET', '/ops/events', 'scheduler'],
  ['GET', `/ops/events/${X}`, 'scheduler'],
  ['POST', '/ops/events', 'scheduler'],
  ['PATCH', `/ops/events/${X}`, 'scheduler'],
  ['POST', `/ops/events/${X}/status`, 'scheduler'],
  ['PUT', `/ops/events/${X}/costs`, 'scheduler'],
  ['POST', `/ops/events/${X}/registrations`, 'scheduler'],
  ['POST', `/ops/events/${X}/registrations/${X}/cancel`, 'scheduler'],
  ['PUT', `/ops/events/${X}/attendance`, 'scheduler'],
  ['POST', `/ops/events/${X}/bill`, 'scheduler'],
  ['GET', '/memberships', 'admin'],
  ['POST', '/memberships/invite', 'admin'],
  ['PATCH', `/memberships/${X}`, 'admin'],
  ['PATCH', `/memberships/${X}/branches`, 'admin'],
  ['DELETE', `/memberships/${X}`, 'admin'],
  ['GET', `/branches/${X}/notification-settings`, 'admin'],
  ['PUT', `/branches/${X}/notification-settings`, 'admin'],
  ['GET', `/branches/${X}/calendar`, 'admin'],
  ['PUT', `/branches/${X}/calendar`, 'admin'],
  ['GET', '/notifications', 'admin'],
  ['POST', '/notifications/run', 'scheduler'],
  ['GET', '/parents', 'viewer'],
  ['GET', `/parents/${X}`, 'viewer'],
  ['POST', '/parents', 'scheduler'],
  ['PATCH', `/parents/${X}`, 'scheduler'],
  ['POST', `/parents/${X}/archive`, 'admin'],
  ['POST', `/parents/${X}/reactivate`, 'admin'],
  ['POST', `/parents/${X}/links`, 'scheduler'],
  ['PATCH', `/parents/${X}/links/${X}`, 'scheduler'],
  ['POST', `/parents/${X}/links/${X}/deactivate`, 'admin'],
  ['GET', '/students', 'viewer'],
  ['GET', `/students/${X}`, 'viewer'],
  ['POST', '/students', 'scheduler'],
  ['PATCH', `/students/${X}`, 'scheduler'],
  ['GET', `/students/${X}/family`, 'viewer'],
  ['GET', '/attendance', 'viewer'],
  ['GET', `/attendance/student/${X}`, 'viewer'],
  ['GET', `/attendance/student/${X}/corrections`, 'viewer'],
  ['PUT', '/attendance', 'scheduler'],
  ['GET', '/transport/buses', 'viewer'],
  ['POST', '/transport/buses', 'scheduler'],
  ['PATCH', `/transport/buses/${X}`, 'scheduler'],
  ['POST', `/transport/buses/${X}/deactivate`, 'scheduler'],
  ['GET', '/transport/stops', 'viewer'],
  ['POST', '/transport/stops', 'scheduler'],
  ['PATCH', `/transport/stops/${X}`, 'scheduler'],
  ['POST', `/transport/stops/${X}/deactivate`, 'scheduler'],
  ['GET', `/branches/${X}/transport-settings`, 'viewer'],
  ['PUT', `/branches/${X}/transport-settings`, 'admin'],
  ['GET', '/audit-log', 'admin'],
  ['GET', '/audit-log/export', 'admin'],
  ['GET', '/search?q=test', 'viewer'],
  ['GET', '/tenant', 'viewer'],
  ['GET', '/admissions/applications', 'scheduler'],
  ['GET', `/admissions/applications/${X}`, 'scheduler'],
  ['POST', '/admissions/applications', 'scheduler'],
  ['PATCH', `/admissions/applications/${X}`, 'scheduler'],
  ['POST', `/admissions/applications/${X}/submit`, 'scheduler'],
  ['POST', `/admissions/applications/${X}/review`, 'scheduler'],
  ['POST', `/admissions/applications/${X}/withdraw`, 'scheduler'],
  ['POST', `/admissions/applications/${X}/convert`, 'scheduler'],
  ['GET', `/documents?ownerType=student&ownerId=${X}`, 'viewer'],
  ['GET', `/documents/${X}/versions`, 'viewer'],
  ['POST', `/documents/${X}/link`, 'viewer'],
  // admissions.manage (scheduler) may upload an applicant's documents;
  // which owners it covers is checked in the handler (documents.test.ts).
  ['POST', '/documents', 'scheduler'],
  ['POST', `/documents/${X}/versions`, 'scheduler'],
  ['POST', `/documents/${X}/verify`, 'admin'],
  ['POST', `/documents/${X}/archive`, 'admin'],
  // Phase 6 communication. The inbox is everyone's own.
  ['GET', '/inbox', 'viewer'],
  ['POST', '/inbox/read-all', 'viewer'],
  ['GET', '/announcements', 'admin'],
  ['GET', `/announcements/${X}`, 'admin'],
  ['POST', '/announcements', 'admin'],
  ['PATCH', `/announcements/${X}`, 'admin'],
  ['POST', `/announcements/${X}/publish`, 'admin'],
  ['POST', `/announcements/${X}/archive`, 'admin'],
  ['GET', '/communication/templates', 'admin'],
  ['PUT', '/communication/templates/fee_reminder', 'admin'],
  ['DELETE', '/communication/templates/fee_reminder', 'admin'],
  ['GET', '/communication/settings', 'admin'],
  ['PUT', '/communication/settings', 'admin'],
  ['GET', '/communication/log', 'admin'],
  ['POST', `/communication/log/${X}/retry`, 'admin'],
  ['POST', '/communication/documents-expiring/send', 'admin'],
  ['GET', '/communication/channels', 'admin'],
  ['GET', '/settings/numbering', 'viewer'],
  // Backlog: health (admins only among the ranks), discipline.
  ['GET', `/students/${X}/alerts`, 'viewer'],
  ['GET', '/imports/students/template', 'scheduler'],
  ['GET', '/id-cards/students', 'viewer'],
  ['GET', '/id-cards/employees', 'admin'],
  ['POST', '/imports/students/preview', 'scheduler'],
  ['POST', '/imports/students/commit', 'scheduler'],
  ['GET', '/imports/employees/template', 'admin'],
  ['POST', '/imports/employees/preview', 'admin'],
  ['POST', '/imports/employees/commit', 'admin'],
  ['GET', `/students/${X}/health`, 'admin'],
  ['PUT', `/students/${X}/health`, 'admin'],
  ['GET', '/clinic/visits', 'admin'],
  ['POST', '/clinic/visits', 'admin'],
  ['GET', '/clinic/alerts', 'admin'],
  ['POST', '/discipline/incidents', 'scheduler'],
  ['GET', '/discipline/incidents', 'scheduler'],
  ['GET', `/discipline/incidents/${X}`, 'scheduler'],
  ['POST', `/discipline/incidents/${X}/actions`, 'admin'],
  ['POST', `/discipline/incidents/${X}/status`, 'admin'],
  ['POST', `/discipline/incidents/${X}/notify`, 'admin'],
  ['PUT', '/settings/numbering/invoiceNumber', 'admin'],
  ['POST', '/communication/test-send', 'admin'],
  ['POST', '/communication/log/retry', 'admin'],
  ['GET', '/finance/reminders', 'admin'],
  ['POST', '/finance/reminders/send', 'admin'],
  ['GET', `/parents/${X}/portal`, 'admin'],
  ['POST', `/parents/${X}/portal/enable`, 'admin'],
  ['POST', `/parents/${X}/portal/resend`, 'admin'],
  ['POST', `/parents/${X}/portal/disable`, 'admin'],
  // Phase 7: the catalog is open to staff; each report needs its module's
  // scopes (FORBIDDEN from the catalog itself when missing).
  ['GET', '/reports/catalog', 'viewer'],
  ['GET', '/reports/students.roster', 'viewer'],
  ['GET', '/reports/attendance.byClass?from=2026-09-01&to=2026-09-30', 'viewer'],
  ['GET', '/reports/admissions.pipeline', 'scheduler'],
  ['GET', '/reports/ops.loans', 'scheduler'],
  ['GET', '/reports/finance.outstanding', 'admin'],
  ['GET', '/reports/hr.staff', 'admin'],
  ['GET', '/reports/students.roster/export?format=csv', 'viewer'],
  ['GET', '/reports/finance.outstanding/export?format=xlsx', 'admin'],
  ['GET', '/reports/schedules', 'admin'],
  ['POST', '/reports/schedules', 'admin'],
  ['PATCH', `/reports/schedules/${X}`, 'admin'],
  ['DELETE', `/reports/schedules/${X}`, 'admin'],
  ['POST', `/reports/schedules/${X}/run`, 'admin'],
  ['GET', '/reports/recipients?key=finance.outstanding', 'admin'],
  ['GET', '/reports/runs', 'viewer'],
  ['GET', `/reports/runs/${X}/file`, 'viewer'],
  // SAMS 9.1: routes the inventory found without a row.
  ['DELETE', `/students/${X}`, 'admin'],
  ['PATCH', '/tenant', 'admin'],
  ['GET', '/dashboard/summary', 'viewer'],
  ['GET', '/settings/lookups/grade', 'viewer'],
  ['POST', '/settings/lookups/grade', 'admin'],
  ['PATCH', `/settings/lookups/grade/${X}`, 'admin'],
  ['POST', `/inbox/${X}/read`, 'viewer'],
  // Any member may raise and follow their own requests; who may see or
  // decide one is per request (approvals.test.ts).
  ['GET', '/approvals/types', 'viewer'],
  ['POST', '/approvals', 'viewer'],
  ['GET', '/approvals', 'viewer'],
  ['GET', `/approvals/${X}`, 'viewer'],
  ['POST', `/approvals/${X}/approve`, 'viewer'],
  ['POST', `/approvals/${X}/reject`, 'viewer'],
  ['POST', `/approvals/${X}/cancel`, 'viewer'],
  // SAMS 11.1 online payments.
  ['GET', '/settings/payments', 'viewer'],
  ['PUT', '/settings/payments', 'admin'],
  ['GET', '/finance/online-payments', 'viewer'],
  ['POST', `/finance/online-payments/${X}/check`, 'viewer'],
  // SAMS 12: the getting-started checklist.
  ['GET', '/onboarding', 'viewer'],
  ['POST', '/finance/invoices/bulk', 'scheduler'],
  ['POST', '/parents/portal/invite-all', 'admin'],
  // SAMS 11.4 canteen: selling is a scope no default rank below admin holds
  // (the Canteen role has it); managing is admin.
  ['GET', '/canteen/products', 'admin'],
  ['POST', '/canteen/products', 'admin'],
  ['PATCH', `/canteen/products/${X}`, 'admin'],
  ['GET', `/canteen/card?card=${X}`, 'admin'],
  ['POST', '/canteen/sales', 'admin'],
  ['POST', `/canteen/sales/${X}/refund`, 'admin'],
  ['GET', '/canteen/summary', 'admin'],
  ['GET', `/canteen/wallets/${X}`, 'admin'],
  ['POST', `/canteen/wallets/${X}/topup`, 'admin'],
  // SAMS 11.3 library desk.
  ['GET', `/ops/library/borrower?card=${X}`, 'scheduler'],
  ['POST', '/ops/library/return-by-barcode', 'scheduler'],
  ['POST', `/ops/library/loans/${X}/bill`, 'scheduler'],
  ['POST', '/ops/library/overdue/notify', 'scheduler'],
  // SAMS 11.2 gradebook: teachers (schedulers) read and enter; admins manage.
  ['GET', '/grades/settings', 'scheduler'],
  ['PUT', '/grades/settings', 'admin'],
  ['GET', `/grades/plans?academicYearId=${X}`, 'scheduler'],
  ['PUT', '/grades/plans', 'admin'],
  ['GET', `/grades/sheet?classId=${X}&subjectCode=math&termId=t1`, 'scheduler'],
  ['PUT', '/grades/sheet', 'scheduler'],
  ['PUT', '/grades/comments', 'scheduler'],
  ['GET', `/grades/results?classId=${X}&termId=t1`, 'scheduler'],
  ['GET', `/grades/report-cards?classId=${X}&termId=t1`, 'scheduler'],
  ['POST', '/grades/release', 'admin'],
  ['POST', '/grades/unrelease', 'admin'],
  // A school's own team (memberships.manage).
  ['GET', '/memberships', 'admin'],
  ['GET', '/memberships/roles', 'admin'],
  ['POST', '/memberships/invite', 'admin'],
  ['PATCH', `/memberships/${X}`, 'admin'],
  ['PATCH', `/memberships/${X}/branches`, 'admin'],
  ['DELETE', `/memberships/${X}`, 'admin'],
]

/** The vendor's console API: platform admins only, never a school's owner. */
export const PLATFORM_ROUTES: [Method, string][] = [
  ['GET', '/admin/tenants'],
  ['GET', `/admin/tenants/${X}`],
  ['POST', '/admin/tenants'],
  ['PATCH', `/admin/tenants/${X}`],
  ['POST', `/admin/tenants/${X}/invite`],
  ['PATCH', `/admin/tenants/${X}/members/${X}`],
  ['DELETE', `/admin/tenants/${X}/members/${X}`],
  ['GET', `/admin/tenants/${X}/api-keys`],
  ['POST', `/admin/tenants/${X}/api-keys`],
  ['DELETE', `/admin/tenants/${X}/api-keys/${X}`],
  ['GET', `/admin/tenants/${X}/branches`],
  ['POST', `/admin/tenants/${X}/branches`],
  ['PATCH', `/admin/tenants/${X}/branches/${X}`],
]

/** Only a parent portal login holds `portal.parent`; no staff rank does. */
export const PORTAL_ROUTES: [Method, string][] = [
  ['GET', '/portal/me'],
  ['GET', `/portal/children/${X}`],
  ['GET', `/portal/children/${X}/finance`],
  ['GET', `/portal/children/${X}/documents`],
  ['POST', `/portal/documents/${X}/link`],
  ['GET', '/portal/announcements'],
  ['POST', `/portal/children/${X}/pay`],
  ['GET', `/portal/payments/${X}`],
  ['GET', `/portal/children/${X}/report-cards`],
  ['GET', `/portal/children/${X}/report-cards/t1`],
  ['GET', `/portal/children/${X}/wallet`],
  ['PUT', `/portal/children/${X}/wallet/controls`],
  ['POST', `/portal/children/${X}/wallet/topup`],
]

