/**
 * SAMS 10.1 — audit actions ("invoice.installments.set") in words, in
 * English or Arabic: the record, then what was done ("Invoice › Installments
 * · Set"). The code stays available as a tooltip and in the audit export.
 * An unknown word shows as itself, so a new action is never hidden.
 */
import type { Lang } from '../i18n/translations'

const WORDS: Record<string, [string, string]> = {
  rehire: ['Rehire', 'إعادة تعيين'],
  accept: ['Accept', 'قبول'],
  accepted: ['Accepted', 'مقبول'],
  reject: ['Reject', 'رفض'],
  rejected: ['Rejected', 'مرفوض'],
  waitlist: ['Waitlist', 'قائمة الانتظار'],
  waitlisted: ['Waitlisted', 'في قائمة الانتظار'],
  reopen: ['Reopen', 'إعادة فتح'],
  close: ['Close', 'إغلاق'],
  closed: ['Closed', 'مغلق'],
  resolved: ['Resolved', 'محلول'],
  cancelled: ['Cancelled', 'ملغى'],
  completed: ['Completed', 'مكتمل'],
  scheduled: ['Scheduled', 'مجدول'],
  postponed: ['Postponed', 'مؤجل'],
  receive: ['Receive', 'استلام'],
  return: ['Return', 'إرجاع'],
  assign: ['Assign', 'تخصيص'],
  dispose: ['Dispose', 'إتلاف'],
  lost: ['Lost', 'مفقود'],
  damaged: ['Damaged', 'تالف'],
  renew: ['Renew', 'تجديد'],
  in: ['Stock in', 'إدخال'],
  out: ['Stock out', 'إخراج'],
  count: ['Count', 'جرد'],
  active: ['Active', 'فعّال'],
  withdrawn: ['Withdrawn', 'منسحب'],
  transferred: ['Transferred', 'منقول'],
  graduated: ['Graduated', 'متخرج'],
  interview: ['Interview', 'مقابلة'],
  offer: ['Offer', 'عرض'],
  enroll: ['Enroll', 'تسجيل'],
  decide: ['Decide', 'قرار'],
  confirm: ['Confirm', 'تأكيد'],
  in_progress: ['In progress', 'قيد التنفيذ'],
  academicYear: ['Academic year', 'العام الدراسي'],
  action: ['Action', 'إجراء'],
  activate: ['Activate', 'تفعيل'],
  adjust: ['Adjust', 'تعديل'],
  announcement: ['Announcement', 'إعلان'],
  application: ['Application', 'طلب التحاق'],
  apply: ['Apply', 'تطبيق'],
  approval: ['Approval', 'موافقة'],
  approve: ['Approve', 'اعتماد'],
  archive: ['Archive', 'أرشفة'],
  asset: ['Asset', 'أصل'],
  attendance: ['Attendance', 'الحضور'],
  bill: ['Bill', 'فوترة'],
  book: ['Book', 'كتاب'],
  bookCopy: ['Book copy', 'نسخة كتاب'],
  branches: ['Branches', 'الفروع'],
  building: ['Building', 'مبنى'],
  bus: ['Bus', 'حافلة'],
  calendar: ['Calendar', 'التقويم'],
  cancel: ['Cancel', 'إلغاء'],
  class: ['Class', 'شعبة'],
  clinic: ['Clinic', 'العيادة'],
  commit: ['Commit', 'تنفيذ'],
  communication: ['Communication', 'التواصل'],
  complete: ['Complete', 'إكمال'],
  contract: ['Contract', 'عقد'],
  convert: ['Convert', 'تحويل'],
  correct: ['Correct', 'تصحيح'],
  costs: ['Costs', 'التكاليف'],
  create: ['Create', 'إنشاء'],
  daily: ['Daily', 'يومي'],
  deactivate: ['Deactivate', 'إيقاف'],
  delete: ['Delete', 'حذف'],
  details: ['Details', 'التفاصيل'],
  disable: ['Disable', 'تعطيل'],
  discount: ['Discount', 'خصم'],
  discountType: ['Discount type', 'نوع الخصم'],
  document: ['Document', 'مستند'],
  documents: ['Documents', 'المستندات'],
  download: ['Download', 'تنزيل'],
  driver: ['Driver', 'سائق'],
  emergencyContacts: ['Emergency contacts', 'جهات الطوارئ'],
  employee: ['Employee', 'موظف'],
  enable: ['Enable', 'تمكين'],
  end: ['End', 'إنهاء'],
  enrollment: ['Enrollment', 'تسجيل'],
  event: ['Event', 'فعالية'],
  expense: ['Expense', 'مصروف'],
  expiring: ['Expiring', 'قرب الانتهاء'],
  export: ['Export', 'تصدير'],
  feeStructure: ['Fee structure', 'هيكل الرسوم'],
  finance: ['Finance', 'المالية'],
  generate: ['Generate', 'توليد'],
  graduate: ['Graduate', 'تخريج'],
  hold: ['Hold', 'تعليق'],
  idcards: ['ID cards', 'البطاقات'],
  import: ['Import', 'استيراد'],
  incident: ['Incident', 'حادثة سلوكية'],
  inventory: ['Inventory', 'المخزون'],
  invite: ['Invite', 'دعوة'],
  invoice: ['Invoice', 'فاتورة'],
  issue: ['Issue', 'إصدار'],
  item: ['Item', 'صنف'],
  leave: ['Leave', 'إجازة'],
  leaveType: ['Leave type', 'نوع الإجازة'],
  library: ['Library', 'المكتبة'],
  linkUser: ['Link user', 'ربط مستخدم'],
  loan: ['Loan', 'إعارة'],
  lookup: ['List item', 'عنصر قائمة'],
  maintenance: ['Maintenance', 'صيانة'],
  membership: ['Team member', 'عضو الفريق'],
  newVersion: ['New version', 'نسخة جديدة'],
  notification: ['Notification', 'إشعار'],
  notificationSettings: ['Notification settings', 'إعدادات الإشعارات'],
  notify: ['Notify', 'إبلاغ'],
  numbering: ['Numbering', 'الترقيم'],
  open: ['Open', 'فتح'],
  parent: ['Parent', 'ولي أمر'],
  parentStudentLink: ['Family link', 'صلة عائلية'],
  pay: ['Pay', 'دفع'],
  payment: ['Payment', 'دفعة'],
  portal: ['Portal', 'البوابة'],
  print: ['Print', 'طباعة'],
  profile: ['Profile', 'الملف'],
  promote: ['Promote', 'ترفيع'],
  publish: ['Publish', 'نشر'],
  reactivate: ['Reactivate', 'إعادة تفعيل'],
  receipt: ['Receipt', 'إيصال'],
  record: ['Record', 'تسجيل'],
  refund: ['Refund', 'استرداد'],
  register: ['Register', 'تسجيل'],
  reminders: ['Reminders', 'التذكيرات'],
  remove: ['Remove', 'إزالة'],
  report: ['Report', 'تقرير'],
  reportSchedule: ['Scheduled report', 'تقرير مجدول'],
  request: ['Request', 'طلب'],
  reset: ['Reset', 'إعادة ضبط'],
  retry: ['Retry', 'إعادة المحاولة'],
  retryAll: ['Retry all', 'إعادة محاولة الكل'],
  revoke: ['Revoke', 'سحب'],
  role: ['Role', 'الدور'],
  rollover: ['Year-end', 'نهاية العام'],
  room: ['Room', 'قاعة'],
  scholarship: ['Scholarship', 'منحة'],
  send: ['Send', 'إرسال'],
  set: ['Set', 'تعيين'],
  setCurrent: ['Set as current', 'تعيين كحالي'],
  settings: ['Settings', 'الإعدادات'],
  staffAttendance: ['Staff attendance', 'حضور الموظفين'],
  start: ['Start', 'بدء'],
  startYear: ['Start year', 'بدء العام'],
  stop: ['Stop', 'إيقاف'],
  student: ['Student', 'طالب'],
  submit: ['Submit', 'تقديم'],
  template: ['Template', 'قالب'],
  tenant: ['School', 'المدرسة'],
  terminate: ['Terminate', 'إنهاء الخدمة'],
  transfer: ['Transfer', 'نقل'],
  transportFee: ['Transport fee', 'رسوم النقل'],
  transportSettings: ['Transport settings', 'إعدادات النقل'],
  unregister: ['Unregister', 'إلغاء التسجيل'],
  update: ['Update', 'تعديل'],
  upload: ['Upload', 'رفع'],
  vendor: ['Vendor', 'مورّد'],
  verify: ['Verify', 'توثيق'],
  visit: ['Visit', 'زيارة'],
  void: ['Void', 'إبطال'],
  withdraw: ['Withdraw', 'سحب'],
}

const word = (w: string, lang: Lang) => {
  const entry = WORDS[w]
  return entry ? entry[lang === 'ar' ? 1 : 0] : w
}

/** "invoice.installments.set" → "Invoice › Installments · Set". */
export function actionLabel(code: string, lang: Lang): string {
  const parts = code.split('.')
  if (parts.length < 2) return word(code, lang)
  const verb = word(parts[parts.length - 1]!, lang)
  const nouns = parts.slice(0, -1).map((p) => word(p, lang))
  return `${nouns.join(' › ')} · ${verb}`
}

